/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MyAppointmentsRouteImport } from './routes/my-appointments'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as DoctorDashboardRouteImport } from './routes/doctor-dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookRouteImport } from './routes/book'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DoctorsDoctorIdRouteImport } from './routes/doctors.$doctorId'

const MyAppointmentsRoute = MyAppointmentsRouteImport.update({
  id: '/my-appointments',
  path: '/my-appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorDashboardRoute = DoctorDashboardRouteImport.update({
  id: '/doctor-dashboard',
  path: '/doctor-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsDoctorIdRoute = DoctorsDoctorIdRouteImport.update({
  id: '/$doctorId',
  path: '/$doctorId',
  getParentRoute: () => DoctorsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/doctor-dashboard': typeof DoctorDashboardRoute
  '/doctors': typeof DoctorsRouteWithChildren
  '/login': typeof LoginRoute
  '/my-appointments': typeof MyAppointmentsRoute
  '/doctors/$doctorId': typeof DoctorsDoctorIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/doctor-dashboard': typeof DoctorDashboardRoute
  '/doctors': typeof DoctorsRouteWithChildren
  '/login': typeof LoginRoute
  '/my-appointments': typeof MyAppointmentsRoute
  '/doctors/$doctorId': typeof DoctorsDoctorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/doctor-dashboard': typeof DoctorDashboardRoute
  '/doctors': typeof DoctorsRouteWithChildren
  '/login': typeof LoginRoute
  '/my-appointments': typeof MyAppointmentsRoute
  '/doctors/$doctorId': typeof DoctorsDoctorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/book'
    | '/contact'
    | '/doctor-dashboard'
    | '/doctors'
    | '/login'
    | '/my-appointments'
    | '/doctors/$doctorId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/book'
    | '/contact'
    | '/doctor-dashboard'
    | '/doctors'
    | '/login'
    | '/my-appointments'
    | '/doctors/$doctorId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/book'
    | '/contact'
    | '/doctor-dashboard'
    | '/doctors'
    | '/login'
    | '/my-appointments'
    | '/doctors/$doctorId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  DoctorDashboardRoute: typeof DoctorDashboardRoute
  DoctorsRoute: typeof DoctorsRouteWithChildren
  LoginRoute: typeof LoginRoute
  MyAppointmentsRoute: typeof MyAppointmentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/my-appointments': {
      id: '/my-appointments'
      path: '/my-appointments'
      fullPath: '/my-appointments'
      preLoaderRoute: typeof MyAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor-dashboard': {
      id: '/doctor-dashboard'
      path: '/doctor-dashboard'
      fullPath: '/doctor-dashboard'
      preLoaderRoute: typeof DoctorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/$doctorId': {
      id: '/doctors/$doctorId'
      path: '/$doctorId'
      fullPath: '/doctors/$doctorId'
      preLoaderRoute: typeof DoctorsDoctorIdRouteImport
      parentRoute: typeof DoctorsRoute
    }
  }
}

interface DoctorsRouteChildren {
  DoctorsDoctorIdRoute: typeof DoctorsDoctorIdRoute
}

const DoctorsRouteChildren: DoctorsRouteChildren = {
  DoctorsDoctorIdRoute: DoctorsDoctorIdRoute,
}

const DoctorsRouteWithChildren =
  DoctorsRoute._addFileChildren(DoctorsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  DoctorDashboardRoute: DoctorDashboardRoute,
  DoctorsRoute: DoctorsRouteWithChildren,
  LoginRoute: LoginRoute,
  MyAppointmentsRoute: MyAppointmentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
